#!/bin/sh
#

if [ -z $XMLBINDING_HOME ]; then
	XMLBINDING_HOME=".";
fi

#java -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=20500,server=y -Djava.ext.dirs=${XMLBINDING_HOME}/lib org.safris.xml.toolkit.binding.Generator "$@"
java -Djava.ext.dirs=${XMLBINDING_HOME}/lib org.safris.xml.toolkit.binding.Generator "$@"
exit $?;
