#!/bin/sh
#

mkdir -p src/main/java/org/safris/xml/tutorial/binding/invoice/
cp $HOME/Projects/org/safris/trunk/xml/tutorial/binding/src/main/java/org/safris/xml/tutorial/binding/invoice/*.java src/main/java/org/safris/xml/tutorial/binding/invoice/

mkdir -p src/main/resources/xsd
cp $HOME/Projects/org/safris/trunk/xml/tutorial/binding/src/main/resources/xsd/invoice.xsd src/main/resources/xsd/

mkdir lib
cp $HOME/Projects/org/safris/trunk/xml/standalone/binding/target/install/lib/xml-toolkit-binding-*.jar lib/
